### ISSUE TITLE
近隣県へのリンク追加

### ISSUE THREAD

**Issue by paichi81** [nishidayoshikatsu/covid19-yamaguchi#101]
## 改善詳細 / Details of Improvement
- 福岡・広島など近隣発生状況にかんたんにアクセスできるようにする

## 期待する見せ方・挙動 / Expected behavior
- 茨城県版のように他県対策サイトリンクページを作成する

![image](https://user-images.githubusercontent.com/4400857/89113650-d7e92400-d4ae-11ea-8dcd-21297f7122ad.png)

**Comment by Hir-Hag** [comment]
@paichi81 
このissueについてですが、
code for japanさんの「StopCovid19 全国版の地域詳細一覧」が存在してるので、
そちらへのlinkを貼ればいいのではないでしょうか.
　https://stopcovid19.code4japan.org/tables/area-tables

**Comment by paichi81** [comment]
該当リンクですが、CfJの東京版オリジナルを元にフォークした自治体へのリンク集となっています。
高知県のように利用していない自治体もあるので、そのような所は県公式サイトへリンクする様にし、全国を網羅したかたちにしています

**Comment by nishidayoshikatsu** [comment]
解決してそうなのでcloseします。
