### ISSUE TITLE
埋め込み用コードのアイコンが正しく表示されない

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#103]
## 起こっている問題 / The Problem
- 開発用サイトで埋め込み用コードを表示すると、LINEやTwitterなどのアイコンがずれてしまっている。本番用では正しく表示されている。

## スクリーンショット / Screenshot

<img width="461" alt="bug" src="https://user-images.githubusercontent.com/54769649/89120479-975eca00-d4f1-11ea-89ec-51291eb90667.png">

## 期待する見せ方・挙動 / Expected Behavior
- 開発用サイトでも埋め込み用コードのアイコンを正しく表示する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 開発用サイトを開く
2. 埋め込み用コードを表示する。

## 動作環境・ブラウザ / Environment
- Windows 
- Chrome

**Comment by paichi81** [comment]
webp形式の画像が不足してるみたいです。
各種SNSのリンクとアイコンを追加する 案1 #99 でも解決します(あるいはwebp画像を /staticに追加)

![image](https://user-images.githubusercontent.com/4400857/90580464-e2702100-e203-11ea-90c8-78bdac6fcb15.png)
