### ISSUE TITLE
「お子様をお持ちの皆様へ」ページ内のリンク切れ

### ISSUE THREAD

**Issue by paichi81** [nishidayoshikatsu/covid19-yamaguchi#107]
## 起こっている問題 / The Problem
- 「お子様をお持ちの皆様へ」ページ内、「3.子育て中の保護者及び子どものための相談窓口について」にあるチラシへのリンクが存在しなくなっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4400857/89841730-b541c400-dbae-11ea-88f7-259f07e316db.png)

## 期待する見せ方・挙動 / Expected Behavior
- 2020/8/11現在、類似するリンクが"県子ども家庭課"内にはないようなのでリンクを除去する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 保護者向けチラシをクリック
2. 子ども向けチラシをクリック

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nishidayoshikatsu** [comment]
開発用サイトにて修正を既に行っているので、このイシューは一旦closeさせていただきます。
https://dev-covid19-yamaguchi.netlify.app/parent
