### ISSUE TITLE
英語版にした際、新型コロナウイルス感染症が心配なときにの、If you are advised to be examined for COVID-19の19のみが改行される

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#108]
## 改善詳細 / Details of Improvement
英語版にした際、新型コロナウイルス感染症が心配なときにの、If you are advised to be examined for COVID-19の19のみが改行される。
## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/54769649/90331443-41108180-dfef-11ea-81ff-a5496f1756d4.png)

## 期待する見せ方・挙動 / Expected behavior
- 改行しないかfor COVID-19を改行する
## 動作環境・ブラウザ / Environment
- Windows10
- Chrome(ズーム100％)

**Comment by atososon** [comment]
たしかに、開いてるブラウザのウィンドウサイズにより改行位置が変わるため許容範囲だと思いますのでCloseします。

**Comment by nishidayoshikatsu** [comment]
@atososon 
issue立てた時と文言が変わっているかと思うので、対応箇所のスクリーンショットを貼り付けておいてもらって、クローズしてもらえると確認しやすいので助かります。

**Comment by nishidayoshikatsu** [comment]
## 現状のflowページのPC版・モバイル版の見え方

以下に貼り付け、UIの確認を行ったところ、特に崩れや不自然な改行等は見つからなかったので、本issueはcloseします。

<img src="https://user-images.githubusercontent.com/42875682/128497992-d00af17c-a4af-402c-8fcd-a9d1048afa94.png" height="800">
<img src="https://user-images.githubusercontent.com/42875682/128498138-51f3cfcc-59f8-46ec-853d-6db562f85e96.png" height="1600">
