### ISSUE TITLE
リンク切れの部分を随時更新する

### ISSUE THREAD

**Issue by nishidayoshikatsu** [nishidayoshikatsu/covid19-yamaguchi#123]
## 起こっている問題 / The Problem
- 山口県公式サイトの変更に伴い、本サイトからのリンクが切れることがあるため、随時更新する

## 期待する見せ方・挙動 / Expected Behavior
- リンク切れを修正

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by paichi81** [comment]
具体的な対応がわからないままアイデアで書いてしまいますが、github actionとかで日次データ更新時にリンク切れ検出して、slackに通知とかされるといいのではないでしょうか。

**Comment by Tomitomi1021** [comment]
#147 で追加した部分にはgithub actionsへの対応は含まれておりませんので対応お願いします．
また，slack botの方は現段階ではまだCOVID-19 YAMAGUCHIワークスペースのbotと紐づいていないのでご了承ください．
※Slack botを作成しIncoming webhookを有効にしてそのURLをlink_check/setting.shのHOOK_URLに代入することで紐づけられます．

**Comment by Tomitomi1021** [comment]
#147 のスクリプトの依存関係に関する補足として使用しているコマンドを列挙しておきます．
- bash
- grep
- sed
- file
- wget
- curl
- test
- sort
- uniq

**Comment by Tomitomi1021** [comment]
> また，slack botの方は現段階ではまだCOVID-19 YAMAGUCHIワークスペースのbotと紐づいていないのでご了承ください．
> ※Slack botを作成しIncoming webhookを有効にしてそのURLをlink_check/setting.shのHOOK_URLに代入することで紐づけられます．
紐づけました．

**Comment by nishidayoshikatsu** [comment]
@Tomitomi1021 さんに書いていただいた[プルリク](#147 )のactions設定を行いました。
毎日0時に実行され、slackのbroken-link-notificationsチャンネルに通知を行います。

**Comment by nishidayoshikatsu** [comment]
現状のエラーログ
![image](https://user-images.githubusercontent.com/42875682/112743630-e521c880-8fd3-11eb-85ef-8d31dd7551ab.png)

**Comment by nishidayoshikatsu** [comment]
エラーは消えたがslackへの通知来てない。多分連携の設定だと思うので？僕の方で確認する。

**Comment by nishidayoshikatsu** [comment]
一旦根本的な原因は解決し、更新完了したためcloseします
