### ISSUE TITLE
twitterのバナーを最新のお知らせに載せる

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#137]
## 改善詳細 / Details of Improvement
- 情報更新が早いtwitterのバナーを最新のお知らせに載せることで手軽に最新情報を閲覧できるようにする

## 期待する見せ方・挙動 / Expected behavior
- twitterのバナーを最新のお知らせに載せる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

**Comment by nishidayoshikatsu** [comment]
[twitterのブランドガイドライン](https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf)に沿った配色が行われていなかったため、配色をガイドライン通りに変更する。
