### ISSUE TITLE
SNSシェアする際に出るURLがNetlifyになっている

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#16]
## 起こっている問題 / The Problem
- Facebook投稿やメッセージ送信の際に表示されるURLが「Netlify」のままになっている

## スクリーンショット / Screenshot
<img width="525" alt="スクリーンショット 2020-03-19 22 18 10" src="https://user-images.githubusercontent.com/2215551/77072194-a8220e00-6a30-11ea-845a-290f79c11f3f.png">

![IMG_5117](https://user-images.githubusercontent.com/2215551/77072160-9b051f00-6a30-11ea-97d9-c3cb33c44b8a.jpg)

## 期待する見せ方・挙動 / Expected Behavior
-  本番URLが正しい？
https://yamaguchi.stopcovid19.jp/

## 起こっている問題の再現手段 / Steps to Reproduce
1. Facebookに新規投稿するとき
2. FacebookメッセンジャーでURLを送信したとき

## 動作環境・ブラウザ / Environment
- macOS / iOS 
- Chrome / Messenger アプリ

**Comment by nishidayoshikatsu** [comment]
修正しました
792e7d613f7cb5c6655e6a6819888e956d3651a3
