### ISSUE TITLE
キャッシュが残っていない状態でwebページにアクセスすると”接続がプライベートではありません”と警告が発生する

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#163]
## 起こっている問題 / The Problem
-  キャッシュが残っていない状態でwebページにアクセスすると”接続がプライベートではありません”と警告が発生する。
- 毎回発生するわけではなく、数回に一度再現する現象である。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/54769649/96701100-2ed60980-13cb-11eb-8871-5d7518a82a4c.png)

## 期待する見せ方・挙動 / Expected Behavior
- ”接続がプライベートではありません”の警告が発生しないように原因を特定し修正する

## 起こっている問題の再現手段 / Steps to Reproduce
1. キャッシュを消す
2. https://yamaguchi.stopcovid19.jp/ にアクセスする

## 動作環境・ブラウザ / Environment
- Windows10 / iOS 14.0.1
- Chrome / Safari /  Edge

**Comment by nishidayoshikatsu** [comment]
こちらでも再現できました
![image](https://user-images.githubusercontent.com/42875682/96710047-79a94e80-13d6-11eb-9121-fbcc0548a1f0.png)

**Comment by nishidayoshikatsu** [comment]
キャッシュを消した際にこのバグと#164 のバグがランダムに発生している。
正常に表示されていることもあり、再現性のないバグである。

**Comment by nishidayoshikatsu** [comment]
サーバー側でLet's encrypt証明書が切れていないことは確認していますが、このバグでは10/16までで期限切れだと言っています。
※再現性のないバグ
![image](https://user-images.githubusercontent.com/42875682/96711365-67c8ab00-13d8-11eb-8c44-630082c5841e.png)

**Comment by Tomitomi1021** [comment]
サーバーにおいてある証明書は期限切れにはなっていないようでした．

**Comment by Tomitomi1021** [comment]
![image](https://user-images.githubusercontent.com/29561529/96860352-9ceb0100-149d-11eb-841a-e71ebd7694f3.png)

opensslコマンドを用いて確認しました．
一回目のコマンド実行では期限が10月15日までになっているようですが，二回目のコマンド実行では12月14までになっています．

時間をおいて実行するとまた一回目のようになるみたいです．

**Comment by Tomitomi1021** [comment]
![image](https://user-images.githubusercontent.com/29561529/96860959-6497f280-149e-11eb-9631-70fe7b075e50.png)

opensslコマンドを用いて確認しました．
一回目の実行では期限が10月15日になっていますが，二回目の実行では期限が12月14日になっています．

また，時間をおいて実行すると，10月15日になっていました．

**Comment by nishidayoshikatsu** [comment]
現在、さくらのクラウド上でサーバーをクローンしローカル環境でssl証明書の期限を確認したところ、正常に更新されていない証明書は確認できませんでした。

以前同様の方法で本番サーバー上で検証した際は、たまに昔の証明書が確認される現象が起こっていませんでしたが、クローン先の環境においては同現象は確認されませんでした。

したがって、本番サーバーの再起動を行い、不具合の改善を行いました。

**Comment by nishidayoshikatsu** [comment]
以下の作業により、本問題は一応解決いたしました。

しかし、原因調査、再発防止、再発時の対応について今後も議論していく必要があると思っているので、issueはまだ開いた状態にしておきます。

上記ついて意見がある方はぜひコメントしていただけると嬉しいです

https://github.com/nishidayoshikatsu/covid19-yamaguchi/issues/163#issuecomment-717449745

**Comment by nishidayoshikatsu** [comment]
この現象は、よくあることらしいので、ssl証明書の期限切れに注意をする。
