### ISSUE TITLE
「最新のお知らせ」表示

### ISSUE THREAD

**Issue by freshcl** [nishidayoshikatsu/covid19-yamaguchi#19]
「最新のお知らせ」を表示してはどうでしょうか？
よろしければ私がやってみます。

**Comment by nishidayoshikatsu** [comment]
現在、「最新のお知らせ」はどの内容をお知らせにのせるか決定していないため削除している状況です。
（東京都のソースからコメントアウトしているだけです。）

内容について少し他の方も含めて話したいので、slackのworkspaceに入ってもらえませんでしょうか？
https://join.slack.com/t/covid19-yamaguchi/shared_invite/zt-cn8cvzep-~YmAzWkf9atGcntCmx_uPg

**Comment by nishidayoshikatsu** [comment]
お知らせ部分の表示

cdc5e43b6ddd7675d74ad60064257f69d2d00516

**Comment by nishidayoshikatsu** [comment]
9c3681bb47888e98cc5ee6c29f7b0484a6e92eb3
