### ISSUE TITLE
英語版で翻訳されていない箇所がある

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#196]
## 起こっている問題 / The Problem
- 英語版 ( https://dev-covid19-yamaguchi.netlify.app/en ) に日本語が残ってしまっている

## スクリーンショット / Screenshot
<img width="1034" alt="スクリーンショット 2021-03-28 14 28 10" src="https://user-images.githubusercontent.com/2215551/112743408-fc5fb680-8fd1-11eb-8e5a-f3cea14f7f4d.png">

## 期待する見せ方・挙動 / Expected Behavior
- 日本語がない状態にする

## 対応方法
- 日本語箇所をキャプチャし、個別翻訳したものをコメントに残す

**Comment by crispytaffy** [comment]
該当箇所: 左カラム
キャプチャ: 
<img width="243" alt="スクリーンショット 2021-03-28 14 33 18" src="https://user-images.githubusercontent.com/2215551/112743472-96bffa00-8fd2-11eb-8bd1-4d488b493450.png">
テキスト: 他都道府県の新型コロナ対策サイト

**Comment by crispytaffy** [comment]
該当箇所: [Updates on COVID-19 in Yamaguchi](https://dev-covid19-yamaguchi.netlify.app/en)内、3箇所
<img width="1029" alt="スクリーンショット 2021-03-28 14 39 12" src="https://user-images.githubusercontent.com/2215551/112743570-66c52680-8fd3-11eb-8871-2f0f04143dbf.png">

テキスト:
- PCR検査実施人数（累計）
- 検査実施人数
- 以下のデータは、「国土交通省 国土数値情報（行政区域）」をもとに本サイトが作成

**Comment by crispytaffy** [comment]
該当箇所: [How to get help if you suspect you have COVID-19](https://dev-covid19-yamaguchi.netlify.app/en/flow)、全体
キャプチャ:
<img width="1044" alt="スクリーンショット 2021-03-28 14 54 40" src="https://user-images.githubusercontent.com/2215551/112743816-9117e380-8fd5-11eb-8d17-1136e9629ff8.png">

テキスト:
※他県を参照して対応

**Comment by crispytaffy** [comment]
> * 他都道府県の新型コロナ対策サイト
Sites of other prefectures and local governments

> * 山口県広報広聴課 公式チャンネル
Yamaguchi Prefecture Public Relations Division 
↑
正式なものがあるかも？
山本さんに正式なものを確認依頼（3/28）

> * 県内Go To Eat情報
Yamaguchi Go To Eat Campaign

**Comment by crispytaffy** [comment]
> * PCR検査実施人数（累計）
Number of tested people (cumulative)

> * 例目
cases

> * 検査実施人数
Number of tested people

> * 以下のデータは、「国土交通省 国土数値情報（行政区域）」をもとに本サイトが作成

**Comment by nishidayoshikatsu** [comment]
> ・ワクチン接種に関するお知らせ
Notice on COVID19 Vaccination

**Comment by crispytaffy** [comment]
> > ・ワクチン接種に関するお知らせ
> > Notice on COVID19 Vaccination

Notice on COVID-19 vaccination

**Comment by nishidayoshikatsu** [comment]
追加翻訳
埼玉県版参考にできそうなのであとで確認します
https://dev-covid19-yamaguchi.netlify.app/en/otherpref
> ・隣接自治体
> ・旧特定警戒都道府県など
> ・その他都道府県

**Comment by nishidayoshikatsu** [comment]
https://www.pref.yamaguchi.lg.jp/cmsdata/a/1/1/a110bc7177f076cdf8b1e90ae006ccfb.pdf

> 山口県新型コロナウイルス感染症専用相談ダイアル
> Yamaguchi Prefecture COVID-19 Hotline

**Comment by nishidayoshikatsu** [comment]
一通りは解決したので、一旦closeします。
また再度翻訳が増えた際にまたreopenします。
