### ISSUE TITLE
ワクチン接種に関するお知らせの追加

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#197]
## 改善詳細 / Details of Improvement
- サイドバーにワクチン接種に関するお知らせを追加する

## 期待する見せ方・挙動 / Expected behavior
- サイドバーにワクチン接種に関するお知らせを追加し、クリックすると山口県のワクチン接種に関するお知らせのページになるようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

**Comment by nishidayoshikatsu** [comment]
現状、山口県ワクチン情報ページに英語版がなく、情報としても海外の方向けの情報は発表されていないため、リンクは日本語版のみ掲載する。
山口県ページで英語版がリリースされたら、英語版にもリンクを掲載する
