### ISSUE TITLE
【当サイトについて】お問い合わせ先をどうするか決める

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#2]
## 改善詳細 / Details of Improvement
「当サイトについて」の末尾にお問い合わせ先を設置する場合、どのメールアドレスにするかを決める必要がある（＝運用体制を作る）

## 他自治体がとっている方法
以下のいずれかが現実的かなと思いますが、どうでしょうか。ご意見ください。

- 問い合わせ先としてFacebookページを作ってそこに誘導し、サイト自体のお知らせも配信する。
→ 情報が増えました等のお知らせがしやすい。ただし、運用負荷が発生する
ex. 当サイトについてのお問い合わせは [JUST道IT Facebookページ](https://www.facebook.com/Justdouit19/)までお願いします。

- Code for といった市民エンジニアが受け皿になっている。宇部にも「Code for Ube」があるのでそこにバックアップに入ってもらい、そのメールアドレスを使わせてもらう
→ 運用も一緒にできるかも。ただし、問い合わせ対応を他の人に依頼することになる

## 他のアイデアも募集します
gmailを作るとか、お問い合わせは載せないなど、他にもアイデアがあると思うので、みんなでどうしたいか決めたいです！

**Comment by nishidayoshikatsu** [comment]
リリース時の初期段階としては、制作側が問い合わせ対応をしたほうがよいと思っているため（デザインの修正やデータの追加などの要望が起こりやすい）、私達で運営するべきかなと思います。

問い合わせ用の媒体としては、サイト修正時のお知らせをしやすいfacebookでいいのではないかと考えています。

**Comment by crispytaffy** [comment]
山梨は有志のプロジェクトの名前を「stopcovid19.yamanashi.dev」というチーム名にしているみたいですね。参考まで。
https://stopcovid19.yamanashi.dev/about
