### ISSUE TITLE
COVID-19関連の動向数値データ等のAPI提供

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#21]
## 改善詳細 / Details of Improvement
- 県公式サイトからスクレイピングしたデータをAPI提供する

## やること
[ ] - data.jsonをgithub pagesからホスティング
[ ] - マニュアルの整備

## 参考）県公式サイトから取得元のURL
- 「陽性患者数」及び「陽性患者の属性」
→「新型コロナウイルス感染症の山口県内での発生について」（https://www.pref.yamaguchi.lg.jp/cms/a15200/kansensyou/koronahassei.html）

- 「検査実施数（累計）」及び「新型コロナ受診相談窓口相談件数（累計）」について
月・水・金曜日に数字の更新（前日までの累計件数を各実施機関等からの報告をもとに県の担当課で取りまとめ）
→「新型コロナウイルスに関連した感染症について」（https://www.pref.yamaguchi.lg.jp/cms/a15200/kansensyou/ncorona.html）

- 県からのお知らせについては、
各部署が新型コロナウイルス関連の情報を県ＨＰ等で発出する都度、
→「新型コロナウイルスに関連する県からのお知らせ」（https://www.pref.yamaguchi.lg.jp/cms/a11000/korona_kanren/kanren_link.html）

**Comment by nishidayoshikatsu** [comment]
「陽性患者数」「検査実施数（累計）」「新型コロナ受診相談窓口相談件数（累計）」の3つのデータについて、github pagesからホスティングすることができた。

他のデータについても、このURLにデータを追加していく。
https://raw.githubusercontent.com/nishidayoshikatsu/covid19-yamaguchi-data/gh-pages/data.json

**Comment by nishidayoshikatsu** [comment]
県との交渉で、オープンデータ化することが決定した。
API提供は行うのか、行わないか、提供をするほど需要があるのかどうかを議論する必要がある。

**Comment by nishidayoshikatsu** [comment]
[新しく作成したリポジトリ](https://github.com/nishidayoshikatsu/covid19-yamaguchi-opendata)でjson apiの提供を開始した
