### ISSUE TITLE
Code for Yamaguchiのバナーを追加

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#213]
## 改善詳細 / Details of Improvement
- Code for Yamaguchiのバナーを追加する

## 期待する見せ方・挙動 / Expected behavior
- さくらインターネット様の下にCode for Yamaguchiのバナーを追加する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

**Comment by nishidayoshikatsu** [comment]
#214 マージ完了
