### ISSUE TITLE
SEO対策

### ISSUE THREAD

**Issue by nishidayoshikatsu** [nishidayoshikatsu/covid19-yamaguchi#23]
## 改善詳細 / Details of Improvement
* 検索した際に上位に表示させる

## やること

* SEO対策を行う

**Comment by Tomitomi1021** [comment]
こちらでは、 #25 のため確認ができないので、できれば正しくmetaタグが生成されているか確認してほしい。

**Comment by nishidayoshikatsu** [comment]
構造化データを追加した
50f8b37d4030a5580108dadd1e8e31295ee9b7fc

**Comment by nishidayoshikatsu** [comment]
「山口　コロナ」等の検索ワードで平均して1ページ目の上から3, 4番目あたりに出てくることを確認した。
