### ISSUE TITLE
docker-compose upがエラーで落ちる

### ISSUE THREAD

**Issue by Tomitomi1021** [nishidayoshikatsu/covid19-yamaguchi#25]
## 起こっている問題 / The Problem
developブランチの直近のコミット( 24fc355 )にて
docker-compose up
を実行したところ、エラーが発生して落ちた。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/29561529/78255760-b42ec500-7532-11ea-8f1b-c54993a3ef39.png)

## 期待する見せ方・挙動 / Expected Behavior
docker-compose up
がエラー無く実行されること。

## 起こっている問題の再現手段 / Steps to Reproduce
少なくとも自分の環境では、 7417813 のコミット以降で発生する。

## 動作環境・ブラウザ / Environment
- docker-compose/ArchLinux

**Comment by nishidayoshikatsu** [comment]
こちらの環境（Ubuntu18.04LTS）では、このissueのバグを再現できていないです。
（キャッシュ削除も試したが同様に再現できていない）

**Comment by nishidayoshikatsu** [comment]
学校にあるPC（Windows10）のVM上のUbuntuを使って試してみたが、同様に再現できていない。
可能性としては、 @Tomitomi1021 の環境依存の問題ではないか確認する必要がある。

**Comment by nomunomu0504** [comment]
node_modules の問題っぽそうなので、プロジェクトディレクトリ直下の `node_modules` フォルダを削除して、再度 `yarn install` を行ってみるのが一番手っ取り早いかもしれないですね。

**Comment by atososon** [comment]
自分のPC（Windows10）のWSL2上のUbuntuを使って試したところ、同様に再現できなかった。

**Comment by Tomitomi1021** [comment]
docker-composeでは相変わらずうまくいきませんが、
@nomunomu0504 さんのyarnを使う方法だとうまくいきました。
ありがとうございました。

**Comment by nomunomu0504** [comment]
おお、そうでしたか。よかったです。

`docker-compose up` のエラーが直らなかったのは、すこし疑問点ですが、 `docker-compose up --force-recreate --build` とかを実行してみてもいいかもですね。
