### ISSUE TITLE
7月30日以降の情報が表示されない。

### ISSUE THREAD

**Issue by Tomitomi1021** [nishidayoshikatsu/covid19-yamaguchi#251]
## 起こっている問題 / The Problem
- 7月30日以降の情報が表示されない。

## スクリーンショット / Screenshot
![スクリーンショット](https://user-images.githubusercontent.com/29561529/128142474-47883aa2-9dd4-4892-adf8-f1a27a777142.png)
![コンソール](https://user-images.githubusercontent.com/29561529/128142545-abee4416-4804-452e-a4b0-d86a1e627b5e.png)

## 期待する見せ方・挙動 / Expected Behavior
- 7月30日以降のデータを表示させる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする。

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by nishidayoshikatsu** [comment]
オープンデータ自体の更新が止まっているようですので、山口県の担当の方に確認します。

**Comment by nishidayoshikatsu** [comment]
@Tomitomi1021 
オープンデータを更新していただいたので、このissueはcloseしますね。
