### ISSUE TITLE
スマートフォンからアクセスができない

### ISSUE THREAD

**Issue by Tomitomi1021** [nishidayoshikatsu/covid19-yamaguchi#262]
## 起こっている問題 / The Problem
- スマートフォンからアクセスができない

## スクリーンショット / Screenshot
![Screenshot_20220626-160815](https://user-images.githubusercontent.com/29561529/175803603-b9fbc307-5f28-445e-bf92-38068d5e1580.png)

## 期待する見せ方・挙動 / Expected Behavior
- スマートフォンでアクセスできるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. スマートフォンでアクセスする

## 動作環境・ブラウザ / Environment
- Android11 
- Google Chrome

**Comment by Tomitomi1021** [comment]
Firefoxの方はアクセスできた。


![Screenshot_20220626-161814.png](https://user-images.githubusercontent.com/29561529/175803824-e2d22f40-54ed-487d-8255-9a7fdcac44b4.png)

**Comment by nisshi-dev** [comment]
私の環境でも再現

ステージング環境（netlify）も同じ挙動ってことはインフラの問題じゃなさそう
キャッシュとかデータ取得の問題っぽい

**Comment by nisshi-dev** [comment]
初期のデータ読み込みのデータが重くなったので初期に一括読み込みでメモリエラーが出てるっぽい

一括でデータ読み込むのやめれば解決しそう
