### ISSUE TITLE
「退院数」の掲出方法についての検討（データの取り扱い、見せ方など）

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#28]
## 改善詳細 / Details of Improvement
- 新型コロナウィルスにかかった人の情報は流れてきてますけど、治った人の情報は流れてきてない
- 東京都では退院数を表示している
→ データ所在と出所が確認できたら、追加方法と見せ方を検討する

## データ現状
- 県庁では退院数を公開する予定はない
- 厚生労働省データはありますが、陽性患者の誰が退院になったか不明。公開は都道府県の感染者情報の公開と比べてタイムラグがある

## 期待する見せ方・挙動 / Expected behavior
- A案
県公式サイトの新型コロナウイルスに関連した感染症についての中にリンクされている、厚労省ページ「国内事例における都道府県別の患者報告数」をスクレイピングして、現在落としている「検査陽性数の状況（添付画像左」の表を作って退院数を表示する
（PDFは更新されるため、福井県では1時間に1回スクレイピングしてるみたいです）
<img width="1085" alt="スクリーンショット 2020-04-07 9 13 26" src="https://user-images.githubusercontent.com/2215551/78618979-f94a5280-78b6-11ea-931f-fdafe449a20a.png">

- B案
もっと詳しく知りたい方は厚生労働省ページで俯瞰データ見れるよということで、表の近くに、「都道府県別の患者報告数、入退院の状況については厚生労働省公式サイトをご確認ください」とリンクする

## データの取り扱いで注意すべきポイント
- 東京都では公表済み
- ただし、陽性患者の属性の表の「退院」の中に亡くなった方が含まれているため、取り扱いはセンシティブ。批判もある。都の発表データであることを説明し理解を得ている。

**Comment by nishidayoshikatsu** [comment]
機械可読性の高そうなデータのため、A案で対応してみます。

**Comment by nishidayoshikatsu** [comment]
このようなレイアウトになりました
![image](https://user-images.githubusercontent.com/42875682/79412707-18489300-7fe1-11ea-97cc-4d32d1f8b2c2.png)

**Comment by nishidayoshikatsu** [comment]
A案で本番環境に入退院データの追加を完了しました。
