### ISSUE TITLE
「最新のお知らせ」の件数が増えたため、減らすなど最適化する

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#29]
## 改善詳細 / Details of Improvement
- 「最新のお知らせ」が増えて、スマホで見るとグラフが結構下の方になっている
→ 最適な件数の検討含めて、改善したいです。

## グラフがみやすい方がいい理由
県公式サイトが落ちていたりトラフィック増えている場合はリンク飛べないこともあり、先にグラフが見えると良い（陽性になった方の居住地を知りたいのだと思うため）

## スクリーンショット / Screenshot
![IMG_5747](https://user-images.githubusercontent.com/2215551/78619329-09aefd00-78b8-11ea-8376-c9133c9c5476.png)

## 期待する見せ方・挙動 / Expected behavior
- 県内の最新感染動向としてみせるための枠なのであれば、「最新の2件のみ」でもいいかも

**Comment by VibaChan** [comment]
提案なのですが、最新のお知らせの部分をスマホの時はスクロールできるように変える形で如何でしょうか？現状その部分でおもくなるわけでもないですし・・・中身いじるよりCSS弄る方が恐らく楽ですので。

<img width="360" alt="コロナページ" src="https://user-images.githubusercontent.com/63274378/78625281-a1b3e300-78c6-11ea-800b-055b4c382e26.png">

感覚的に、高さを250pxとれば問題なさそうな気がします。
こんな感じのCSSですね。。
```
@media screen and (min-width: 575px) {
div.WhatsNew {
height:250px;
overflow: scroll;
}
}
```
