### ISSUE TITLE
Firefoxで見た場合、陽性患者の属性の表の公表日が昇順に表示される

### ISSUE THREAD

**Issue by atososon** [nishidayoshikatsu/covid19-yamaguchi#32]
## 起こっている問題 / The Problem
Firefoxで見た場合、陽性患者の属性の表の公表日が昇順で表示される。

## 期待する見せ方・挙動 / Expected Behavior
Firefoxで見た場合でも降順で表示される。

## 起こっている問題の再現手段 / Steps to Reproduce
Firefoxで見る。

## 動作環境・ブラウザ / Environment
-Firefox
(Edge,Chrome,Safariの場合は降順で表示されることを確認)

**Comment by Hayato07** [comment]
こちら対応しても大丈夫でしょうか？

**Comment by nishidayoshikatsu** [comment]
@Hayato07 
対応していただきありがとうございます！
現在完全自動化に向けた作業の方をやっているので、マージまで少々お待ちください。

**Comment by Hayato07** [comment]
@nishidayoshikatsu 
承知いたしました。よろしくおねがいいたします。
また、修正内容に何か問題ありましたら、連絡いただければ対応いたします。

**Comment by nishidayoshikatsu** [comment]
無事、firefoxでも昇順に表示されていることを確認
![image](https://user-images.githubusercontent.com/42875682/80452174-a49f7200-8960-11ea-8a3b-a856d747c86b.png)

@Hayato07 
マージ完了しました！
ご協力ありがとうございました！
