### ISSUE TITLE
山口県版の「新型コロナウイルス感染症が心配なときに」のフローを作る

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#33]
## 改善詳細 / Details of Improvement
- 感染者が増えてきているので、山口県版の「新型コロナウイルス感染症が心配なときに」のフローを作りたい
参考）https://stopcovid19.metro.tokyo.lg.jp/flow

## 期待する見せ方・挙動 / Expected behavior
- 基本的な流れは東京のフローと同様
- 問い合わせ先が異なる（以下）
https://www.pref.yamaguchi.lg.jp/cms/a11000/sodan/koronasoudan.html

**Comment by KeisukeSawa** [comment]
@crispytaffy @nishidayoshikatsu 
「新型コロナウイルス感染症が心配なときに」山口県版を追加したので問題がなければmargeお願いいたします。
何か問題があれば言ってください。

**Comment by nishidayoshikatsu** [comment]
@KeisukeSawa

**Comment by nishidayoshikatsu** [comment]
@KeisukeSawa 対応遅くなりました。マージ完了しました。
