### ISSUE TITLE
【新型コロナウイルス感染症が心配なときに】Flowの修正をどうするか

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#4]
## 改善詳細 / Details of Improvement
県が開示しているフローに該当する情報がないため、全てを精査するのが難しい。
県や保健所のリンクに差し替えた方がいいかもしれません。

## 他自治体の動き
- 有志で開発している奈良県はリンクを外している
- 福岡市は別のリンクに置き換えている（「[こんな方はご注意ください](https://www.city.fukuoka.lg.jp/hofuku/hokenyobo/health/kansen/nCorV.html#kgkd)」）

## 提案
保健所へのリンクに差し替える
http://kanpoken.pref.yamaguchi.lg.jp/jyoho/page5-7/page5-7-31.html

**Comment by nishidayoshikatsu** [comment]
Flowの箇所は保健所のリンクに差し替えます。
しかしそうなると、「新型コロナウイルス感染症に関する相談窓口」に該当する情報が見つけにくくなってしまいますね。
サイドバーの項目に「新型コロナウイルスに関する相談」を追加したほうがよさそうですかね？

**Comment by crispytaffy** [comment]
たしかに、必要ですね。ご提案いただいた項目を追加いただくのがいいと思います！

**Comment by nishidayoshikatsu** [comment]
とりあえずflow部分を削除し保健所のリンクと相談窓口へのリンクを追加しました
6faf4ba
