### ISSUE TITLE
flowの東京版の変更を取り込む

### ISSUE THREAD

**Issue by nishidayoshikatsu** [nishidayoshikatsu/covid19-yamaguchi#44]
## 改善詳細 / Details of Improvement
- 東京都版のflowはデザインが改善されているため、それらを取り込みたい

## スクリーンショット / Screenshot
- 山口県版のflow
![image](https://user-images.githubusercontent.com/42875682/80226408-48e69780-8687-11ea-81c1-55e17ecc0c76.png)

- 東京都版のflow
![image](https://user-images.githubusercontent.com/42875682/80226512-6c114700-8687-11ea-9df5-c8ad27c2409c.png)

## 期待する見せ方・挙動 / Expected behavior
- 東京都版の変更をcherry-pickで取り込む

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by OshaToma** [comment]
こんにちは。
こちらの依頼、対応させていただきたいと思います。

東京都のflowを山口県の物と差し替える認識ですが、相違ありませんでしょうか？
一旦、その流れで対応を進めていきたいと思います。

**Comment by nishidayoshikatsu** [comment]
@OshaToma 
ありがとうございます。
その認識で大丈夫です。
よろしくお願いします。

**Comment by OshaToma** [comment]
ご返信ありがとうございます。
修正案、アップさせていただきました。

https://github.com/nishidayoshikatsu/covid19-yamaguchi/pull/56

**Comment by OshaToma** [comment]
すみません、一旦下げさせていただきました＞＜

**Comment by OshaToma** [comment]
おまたせしました。
修正しましたので、ご確認ください。
