### ISSUE TITLE
OGP画像が東京都のままになっている

### ISSUE THREAD

**Issue by nishidayoshikatsu** [nishidayoshikatsu/covid19-yamaguchi#5]
## 起こっている問題 / The Problem

OGP画像が東京都のままになっている。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/42875682/76781336-eaa9d780-67f1-11ea-8e13-91286722df9a.png)

## 期待する見せ方・挙動 / Expected Behavior

山口県版のOGPを反映させたい

## 起こっている問題の再現手段 / Steps to Reproduce

SNS等に以下のURLを貼る
https://dev-covid19-yamaguchi.netlify.com/

## 動作環境・ブラウザ / Environment
- Ubuntu18.04LTS
- Chrome Browse

**Comment by crispytaffy** [comment]
キャッシュ更新すれば改善されるでしょうか。

**Comment by Tomitomi1021** [comment]
自分も手元で試しましたが、ちゃんと山口県になってました。
おそらく @crispytaffy  さんがおっしゃっているとおりキャッシュの問題ではないかと思います。
<img width="474" alt="ss" src="https://user-images.githubusercontent.com/29561529/76817243-ab0cdb00-6845-11ea-900f-d3f31a8612d8.PNG">

**Comment by Tomitomi1021** [comment]
手元で試してみたところ、ちゃんと山口県になってました。
<img width="474" alt="ss" src="https://user-images.githubusercontent.com/29561529/76817616-bc0a1c00-6846-11ea-9fe4-30f022893729.PNG">

**Comment by nishidayoshikatsu** [comment]
@Tomitomi1021 
あれ、ほんとですね
Github Actionsの反映が遅かったせいで確認できなかったようです。
