### ISSUE TITLE
【ファビコン】東京都のままになっている

### ISSUE THREAD

**Issue by crispytaffy** [nishidayoshikatsu/covid19-yamaguchi#6]
## 起こっている問題 / The Problem
- ファビコンが東京都のままで表示されている

## スクリーンショット / Screenshot
<img width="329" alt="スクリーンショット 2020-03-17 21 40 45" src="https://user-images.githubusercontent.com/2215551/76857078-1089b780-6898-11ea-9b88-aa2c2ec2bef9.png">

## 期待する見せ方・挙動
フグのマークになる
![logo_fuku](https://user-images.githubusercontent.com/2215551/76857194-4d55ae80-6898-11ea-9dc0-55f4e434cc90.jpg)

## 動作環境・ブラウザ / Environment
- macOS
- Chrome バージョン: 80.0.3987.132（Official Build） （64 ビット）

**Comment by nishidayoshikatsu** [comment]
@crispytaffy 

下記の環境で動かしたところ、faviconは正常に表示されました

* Ubuntu 18.04LTS
* Chrome バージョン：79.0.3945.88（Official Build） （64 ビット）
![image](https://user-images.githubusercontent.com/42875682/76858960-c0145900-689b-11ea-8f44-dd2cd0360382.png)

Chromeバージョンの可能性はあまり考えられないので、再度コードを見直してみます。

**Comment by crispytaffy** [comment]
Chromeキャッシュの問題でした。クリアしたら解決しました。
お騒がせしました。
