### ISSUE TITLE
各種SNSのリンクとアイコンを追加する

### ISSUE THREAD

**Issue by KeisukeSawa** [nishidayoshikatsu/covid19-yamaguchi#92]
## 改善詳細 / Details of Improvement
現状、バナーには
山口県新型コロナウイルス感染症対策本部 公式LINE  
山口県新型コロナウイルス感染症対策本部 公式twitter  
は記載されているが、下部のSNSアイコンにはないので追加したい。

Youtubeは山口県広報広聴課のYoutubeがあるのでリンクを追加するとよいと思う。
https://www.youtube.com/channel/UCukxs2WSvAbgAweFsj8k5Cw

## スクリーンショット / Screenshot
東京都版参考
![キャプチャ](https://user-images.githubusercontent.com/21189750/88454138-46732400-cea8-11ea-8419-e7b14cedb8e9.PNG)

**Comment by paichi81** [comment]
Slackのほうで報告しましたが、2パターン案をつくってみました。
