### ISSUE TITLE
ご家庭でのマスクの捨て方を追加

### ISSUE THREAD

**Issue by KeisukeSawa** [nishidayoshikatsu/covid19-yamaguchi#95]
## 改善詳細 / Details of Improvement
東京都版にある「家庭でのマスクの捨て方」という項目をメニューに追加する
リンク先：https://www.kankyo.metro.tokyo.lg.jp/resource/500200a20200221162304660.files/200327_chirashi.pdf

## スクリーンショット / Screenshot
東京都版参考
![キャプチャ](https://user-images.githubusercontent.com/21189750/88454372-217fb080-ceaa-11ea-9d2e-5fc11ad62551.PNG)

**Comment by Himeyama** [comment]
追加します

**Comment by lovechoco** [comment]
MyPCの容量の関係で、開発環境を作ってテストするところまでは出来てないものの、
たぶん下記Pathのファイル内を一部を次のように書き替えれば、
意図するカタチになると思われるヨ.（中途半端でスマヌ）
　- components/SideNavigation.vue　
～～～～～
[変更前（現在）]
```
        // {
        //   icon: 'MaskTrashIcon',
        //   title: this.$t('ご家庭でのマスク等の捨て方'),
        //   link:
        //     'https://www.kankyo.metro.tokyo.lg.jp/resource/500200a20200221162304660.files/200327_chirashi.pdf',
        //   divider: true
        // },
```
　↓↓↓
[変更後]
```
         {
           icon: 'MaskTrashIcon',
           title: this.$t('ご家庭でのマスク等の捨て方'),
           link:
             'https://www.kankyo.metro.tokyo.lg.jp/resource/500200a20200221162304660.files/200327_chirashi.pdf',
           divider: true
         },
```
