### ISSUE TITLE
「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」の横に「相談の手順を見る」ボタンを追加

### ISSUE THREAD

**Issue by KeisukeSawa** [nishidayoshikatsu/covid19-yamaguchi#96]
## 改善詳細 / Details of Improvement
「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」というバナーの横に「相談の手順を見る」ボタンを追加する。
ボタンのリンク先は、flowページ（新型コロナウイルス感染症が心配なときに）に飛ぶようにする。

## スクリーンショット / Screenshot
東京都版参考
![キャプチャ](https://user-images.githubusercontent.com/21189750/88454485-09f4f780-ceab-11ea-8c17-62c4180d9d77.PNG)

**Comment by lovechoco** [comment]
MyPCの容量の関係で、開発環境を作ってテストするところまでは出来てないものの、
たぶん下記Pathのファイル内を一部を次のように書き替えれば、
意図するカタチになると思われるヨ.（中途半端でスマヌ）
　- pages/index.vue　
（"components/StaticInfo.vue"の変更は不要なハズ.）
～～～～～
[変更前（現在）]
```
    <static-info
      class="mb-4"
      :urlNotUse="localePath('/flow')"
      url="https://www.pref.yamaguchi.lg.jp/cms/a10000/korona2020/202004240002.html"
      :text="$t('自分や家族の症状に不安や心配があればまずは電話相談をどうぞ')"
    />
```
　↓↓↓
[変更後]
```
    <static-info
      class="mb-4"
      :urlNotUse="localePath('/flow')"
      url="https://www.pref.yamaguchi.lg.jp/cms/a10000/korona2020/202004240002.html"
      :text="$t('自分や家族の症状に不安や心配があればまずは電話相談をどうぞ')"
      :btn-text="$t('相談の手順を見る')"
    />
```

**Comment by nishidayoshikatsu** [comment]
一旦保留。
