### ISSUE TITLE
メニューボタンを押した際の動作がおかしい

### ISSUE THREAD

**Issue by KeisukeSawa** [nishidayoshikatsu/covid19-yamaguchi#98]
## 起こっている問題 / The Problem
画面が小さくなった時およびスマホ版において以下の動作を行ったときの動作にバグがある。
１．山口県内の最新感染動向ページにいく
２．一番下までスクロール
![キャプチャ](https://user-images.githubusercontent.com/21189750/88455486-9d7cf700-ceb0-11ea-9793-8dffc8ad560a.PNG)
３．メニューバーで「山口県内の最新感染動向ページ」ボタンを押す。
４．以下のようになる。
![キャプチャ](https://user-images.githubusercontent.com/21189750/88455509-c3a29700-ceb0-11ea-9059-f03ac83fc084.PNG)

上記のように画面の先頭に飛ばずに中途半端なところに飛んでしまう。  

このバグは制作ページ全てに該当する。  

## 期待する見せ方・挙動 / Expected Behavior

それぞれの画面の先頭に飛ばす、もしくは見ていたところにとどまるようにする。

**Comment by atososon** [comment]
iPhone7 
iOS14.2 
Safari　Chrome
で試しましたが同様なバグが確認できました

**Comment by Tomitomi1021** [comment]
Google Chromeの検証機能で同様のバグを確認

https://user-images.githubusercontent.com/29561529/102885850-5f9ff100-4497-11eb-9dec-baa87383ff8e.mp4

**Comment by gunsow911** [comment]
突然失礼します。
layouts/default.vue にある
```
<main class="mainContainer" :class="{ open: isOpenNavigation }">
```
の
```
:class="{ open: isOpenNavigation }
```
 は、ナビゲーションオープン時に高さを100vhにしていますが、このときmainContainerの高さが強制的に100vhになってしまうので位置が変になるんじゃないかと思います。
